### PR TITLE
Lf-548: transferto redesign

### PR DESCRIPTION
**Pull request by Addminus**
image

Figma: https://www.figma.com/file/YXtJoxKyLwN5Z56vc34Y88/Transferto-(Website)?node-id=3830%3A38819
Intermediate Swap Widget

### CODE REVIEW

**Review by maxklenk — CHANGES_REQUESTED** [review]
Design:
Swap 3

Thanks, this fits already better to the new LI.FI brand.
The design contains some additional changes I would like to see in the implementation as well:
- box shadow of the form
```
box-shadow: 0px 12px 88px -33px rgba(0, 0, 0, 0.17);
```
The whole page has a background color with linear gradient. Either set it for the whole page, or only for the content and give the header a fixe background color.
```
background: linear-gradient(180deg, #F6F3F2 0%, rgba(246, 243, 242, 0) 100%);
```
- the button padding in the header
- I would like to remove the about page and instead link it to `https://li.fi`

**Comment by Addminus** [comment]
> Design: Swap 3
> 
> Thanks, this fits already better to the new LI.FI brand. The design contains some additional changes I would like to see in the implementation as well:
> 
> * box shadow of the form
> 
> ```
> box-shadow: 0px 12px 88px -33px rgba(0, 0, 0, 0.17);
> ```
> 
> The whole page has a background color with linear gradient. Either set it for the whole page, or only for the content and give the header a fixe background color.
> 
> ```
> background: linear-gradient(180deg, #F6F3F2 0%, rgba(246, 243, 242, 0) 100%);
> ```
> 
> * the button padding in the header
> * I would like to remove the about page and instead link it to `https://li.fi`

**Comment by Addminus** [comment]
There has been some confusion with the restructuring of the Figma Project. Some changes to it got lost during the project migration. I have coordinated with the design team and have all the designs now. I see the missing points and will update this PR.

**Review by maxklenk — APPROVED** [review]
Nice, thanks for the improvements.

**Pull request merged**
